version: '3'

services:
  db:
    image: mysql
    container_name: 'mysql-db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testDocker

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080

    links:
      - 'db:localhost'
